dist: bionic

language: c++

if: commit_message =~ /_BUILD/


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-7
    - libdlib-dev
    - libopenblas-dev


script:
- cmake .
- cmake --build .
- cmake --build . --target package


deploy:
  - provider: script
    skip_cleanup: true
    script:
    - curl -T realty-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uandrewp83:$BINTRAY_API_KEY "https://api.bintray.com/content/andrewp83/otus-cpp/realty/$TRAVIS_BUILD_NUMBER/realty-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
    on:
      branch: homework_16
